
namespace ERP.Module.Enum.NhanSu
{
    public enum ManageKeyEnum : byte
    {
        MaNhanVien,
        SoHopDongLamViec,
        SoHopDongThuViec,
        SoPhuLucHopDong,
        SoHopDongKhoan,
        SoHopDongThinhGiang,
        MaKhachHang,
        MaHoSo,
        MaHoaDonHocPhi,
        MaBienLaiHocPhi,
        //
        SoDonDatHang,
        SoDonHangMua,
        SoDonHangTra,
        SoHoaDonKho,
        SoHopDongMuaBan,
        SoPhieuNhap,
        SoPhieuXuat,
        //Kho bếp
        Bep_SoDonDatHangDuTru,
        Bep_SoDonDeNghiMuaHang,
        Bep_SoDonDeNghiXuatKho,
        //
        MaHocSinh,
        //
        MaPhieuChi,
        //
        MaKyHieuBienLai,
        //TSCD
        SoDieuChuyenTS,
        SoBienBanDenBuTS,
        SoBienBanTraTS,
        SoBienBanNghiemThuTS,
        SoBienBanSuaChuaTS,
        SoBienBanThanhLyTS,
        SoChungTuGhiTangTS,
        SoDeNghiCungCapTS,
        SoDeNghiThueTS,
        SoDeNghiChoThueTS,
        SoDeNghiThanhLyTS,
        SoToTrinhThanhLyTS,
        SoPhieuYeuCauSuaChuaTS,
        //CCDC
        SoDieuChuyenCCDC,
        SoBienBanThanhLyCCDC,
        SoChungTuGhiTangCCDC,
        SoDeNghiCungCapCCDC,
        SoDeNghiThanhLyCCDC,
        SoToTrinhThanhLyCCDC,
        SoBienBanNghiemThuCCDC,
        SoBienBanSuaChuaCCDC,
        SoPhieuYeuCauSuaChuaCCDC,
        //VT
        SoDeNghiCungCapVT,
        // Tuyển sinh
        MaDanhSachCho,
        MaDuThi,
        MaMember
    }
}
